services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy_data:/data
      - ./volumes/caddy_config:/config
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - main-app
      - polyomino-app
      - color-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
    expose:
      - "80"
      - "443"
    restart: unless-stopped

  main-app:
    build:
      context: ./apps/main
      dockerfile: ../Dockerfile
    container_name: main-app
    environment:
      - METADATA_BASE=${METADATA_BASE}
    networks:
      - app-network
    expose:
      - "3000"
    restart: unless-stopped

  polyomino-app:
    build:
      context: ./apps/polyomino
      dockerfile: ../Dockerfile
    container_name: polyomino-app
    environment:
      - METADATA_BASE=${METADATA_BASE}
    networks:
      - app-network
    expose:
      - "3000"
    restart: unless-stopped

  color-app:
    build:
      context: ./apps/color
      dockerfile: ../Dockerfile
    container_name: color-app
    environment:
      - METADATA_BASE=${METADATA_BASE}
    networks:
      - app-network
    expose:
      - "3000"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
